USE CSE_3A_128


--EMPLOYEE_LOG (LOGID, EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)

CREATE TABLE EMPLOYEE_LOG
(
    LOGID INT IDENTITY(1,1),
    EID INT,
    OLDVALUE VARCHAR(100),
    NEWVALUE VARCHAR(100),
    FIELDNAME VARCHAR(50),
    OPERATIONTYPE VARCHAR(20),
    LOGDATE DATETIME
)


--From the table EMPLOYEE perform the following queries:

--1. Create trigger for printing message after employee record insertion.

CREATE OR ALTER TRIGGER TR_INSERT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
	PRINT 'EMPLOYEE RECORD INSERTED SUCCESSFULLY.'
END

DROP TRIGGER TR_INSERT


--2. Create trigger for printing message after employee record update.

CREATE OR ALTER TRIGGER TR_UPDATE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
	PRINT 'EMPLOYEE RECORD UPDATED SUCCESSFULLY.'
END

DROP TRIGGER TR_UPDATE


--3. Create trigger for printing message after employee record deletion.

CREATE OR ALTER TRIGGER TR_DELETE
ON EMPLOYEE
AFTER DELETE
AS
BEGIN
	PRINT 'EMPLOYEE RECORD DELETED SUCCESSFULLY.'
END

DROP TRIGGER TR_DELETE


--4. Create trigger for printing message after employee salary increment.

CREATE OR ALTER TRIGGER TR_INC_SALARY
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
	IF(UPDATE(SALARY))
	PRINT 'SALARY UPDATED'
END

DROP TRIGGER TR_INC_SALARY


--5. Create trigger for automatically converting CITY names into uppercase during insertion.

--FOR A SINGLE ROW

CREATE OR ALTER TRIGGER TR_CITY_CONVERT
ON EMPLOYEE
FOR INSERT
AS
BEGIN
	DECLARE @CITY VARCHAR(30)
	DECLARE @EID INT

	SELECT @CITY = CITY FROM INSERTED
	SELECT @EID = EID FROM INSERTED

	UPDATE EMPLOYEE
	SET CITY = UPPER(@CITY)
	WHERE EID = @EID
END

DROP TRIGGER TR_CITY_CONVERT

--------------------- OR ----------------------

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_CITY_CONVERT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    UPDATE E
    SET E.CITY = UPPER(E.CITY)
    FROM EMPLOYEE E
    INNER JOIN INSERTED I
    ON E.EID = I.EID
END

DROP TRIGGER TR_CITY_CONVERT



--6. Create trigger for updating employee city and printing old city and new city name.

--FOR A SINGLE ROW

CREATE OR ALTER TRIGGER TR_PRINT_CITY
ON EMPLOYEE
FOR UPDATE
AS
BEGIN
	DECLARE @CITY1 VARCHAR(20)
	DECLARE @CITY2 VARCHAR(20)
	DECLARE @EID INT

	SELECT @CITY1 = CITY FROM INSERTED
	SELECT @CITY2 = CITY FROM DELETED
	SELECT @EID = EID FROM INSERTED

	PRINT 'EID : ' + CAST(@EID AS VARCHAR(10))
	PRINT 'OLD CITY' + @CITY2
	PRINT 'NEW CITY' + @CITY1
END

DROP TRIGGER TR_PRINT_CITY

-------------------------- OR ------------------------------

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_PRINT_CITY
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    IF UPDATE(CITY)
    BEGIN
        SELECT
            I.EID,
            'OLD CITY : ' + ISNULL(D.CITY, 'NULL') AS OLD_CITY,
            'NEW CITY : ' + ISNULL(I.CITY, 'NULL') AS NEW_CITY
        FROM INSERTED I
        INNER JOIN DELETED D
        ON I.EID = D.EID
    END
END

DROP TRIGGER TR_PRINT_CITY



--7. Create trigger for automatically setting CITY as 'RAJKOT' if no city value is entered during employee insertion.

--FOR A SINGLE ROW

CREATE OR ALTER TRIGGER TR_CITY_DEFAULT
ON EMPLOYEE
FOR INSERT
AS
BEGIN
	DECLARE @CITY VARCHAR(20)
	DECLARE @EID INT

	SELECT @CITY = CITY FROM INSERTED
    SELECT @EID = EID FROM INSERTED

	IF (@CITY IS NULL)
	BEGIN
		UPDATE EMPLOYEE
		SET CITY = 'RAJKOT'
		WHERE EID = @EID
	END
END

DROP TRIGGER TR_CITY_DEFAULT

-------------------- OR --------------------

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_CITY_DEFAULT
ON EMPLOYEE
FOR INSERT
AS
BEGIN
    UPDATE E
    SET E.CITY = 'RAJKOT'
    FROM EMPLOYEE E
    INNER JOIN INSERTED I
    ON E.EID = I.EID
    WHERE I.CITY IS NULL
END

DROP TRIGGER TR_CITY_DEFAULT



--8. Create trigger for automatically adding current year in JOININGYEAR if no value is entered.

--FOR A SINGLE ROW

CREATE OR ALTER TRIGGER TR_JOININGYEAR
ON EMPLOYEE
FOR INSERT
AS
BEGIN
	DECLARE @YEAR INT
	DECLARE @EID INT

	SELECT @YEAR = JOININGYEAR FROM INSERTED
	SELECT @EID = EID FROM INSERTED

	IF (@YEAR IS NULL)
	BEGIN
		UPDATE EMPLOYEE
		SET JOININGYEAR = YEAR(GETDATE())
		WHERE EID = @EID
	END
END

DROP TRIGGER TR_JOININGYEAR

---------------------- OR ------------------------

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_JOININGYEAR
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    UPDATE E
    SET E.JOININGYEAR = YEAR(GETDATE())
    FROM EMPLOYEE E
    INNER JOIN INSERTED I
    ON E.EID = I.EID
    WHERE I.JOININGYEAR IS NULL
END

DROP TRIGGER TR_JOININGYEAR



--9. Create trigger for printing employee full name after new employee insertion.

--FOR A SINGLE ROW

CREATE OR ALTER TRIGGER TR_NEW_EMPLOYEE
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
	DECLARE @FIRST VARCHAR(20)
	DECLARE @LAST VARCHAR(20)
	DECLARE @EID INT

	SELECT @FIRST = FIRSTNAME FROM INSERTED
	SELECT @LAST = LASTNAME FROM INSERTED
	SELECT @EID = EID FROM INSERTED
	
	PRINT 'EMPLOYEE RECORD INSERTED SUCCESSFULLY.'
	PRINT 'FULL NAME : ' + @FIRST + ' ' + @LAST
END

DROP TRIGGER TR_NEW_EMPLOYEE

------------------------------ OR -------------------------------

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_NEW_EMPLOYEE
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    SELECT
        'EMPLOYEE RECORD INSERTED SUCCESSFULLY.' AS MESSAGE,
        'FULL NAME : ' +
        ISNULL(FIRSTNAME, '') + ' ' +
        ISNULL(LASTNAME, '') AS FULL_NAME
    FROM INSERTED
END

DROP TRIGGER TR_NEW_EMPLOYEE



--10. Create trigger for automatically assigning department as ‘GENERAL’ if DEPARTMENT value is NULL.

--FOR A SINGLE ROW

CREATE OR ALTER TRIGGER TR_DEPARTMENT
ON EMPLOYEE
FOR INSERT
AS
BEGIN
	DECLARE @DEPARTMENT VARCHAR(20)
	DECLARE @EID INT

	SELECT @DEPARTMENT = DEPARTMENT FROM INSERTED
	SELECT @EID = EID FROM INSERTED

	IF (@DEPARTMENT IS NULL)
	BEGIN
		UPDATE EMPLOYEE
		SET DEPARTMENT = 'GENERAL'
		WHERE EID = @EID
	END
END

DROP TRIGGER TR_DEPARTMENT

--------------------------- OR ----------------------------

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_DEPARTMENT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    UPDATE E
    SET E.DEPARTMENT = 'GENERAL'
    FROM EMPLOYEE E
    INNER JOIN INSERTED I
    ON E.EID = I.EID
    WHERE I.DEPARTMENT IS NULL
END

DROP TRIGGER TR_DEPARTMENT



--11. Create trigger for storing updated employee details such as EID, old salary, new salary, old department,
--new department, and update date into EMPLOYEE_UPDATE_LOG table.

CREATE TABLE EMPLOYEE_UPDATE_LOG
(
    LOGID INT IDENTITY(1,1),
    EID INT,
    OLDSALARY DECIMAL(10,2),
    NEWSALARY DECIMAL(10,2),
    OLDDEPARTMENT VARCHAR(100),
    NEWDEPARTMENT VARCHAR(100),
    UPDATEDATE DATETIME
)

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_EMPLOYEE_UPDATE_LOG
ON EMPLOYEE
FOR UPDATE
AS
BEGIN
    INSERT INTO EMPLOYEE_UPDATE_LOG
    (
        EID, OLDSALARY, NEWSALARY,
        OLDDEPARTMENT, NEWDEPARTMENT, UPDATEDATE
    )
    SELECT
        D.EID, D.SALARY, I.SALARY,
        D.DEPARTMENT, I.DEPARTMENT, GETDATE()
    FROM DELETED D
    INNER JOIN INSERTED I
    ON D.EID = I.EID
END

DROP TRIGGER TR_EMPLOYEE_UPDATE_LOG



--12. Create trigger for storing newly inserted employee details with insertion date into EMPLOYEE_INSERT_LOG table.

CREATE TABLE EMPLOYEE_INSERT_LOG
(
    LOGID INT IDENTITY(1,1),
    EID INT,
    FIRSTNAME VARCHAR(100),
    LASTNAME VARCHAR(100),
    SALARY DECIMAL(10,2),
    DEPARTMENT VARCHAR(100),
    CITY VARCHAR(100),
    GENDER VARCHAR(20),
    INSERTDATE DATETIME
)

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_EMPLOYEE_INSERT_LOG
ON EMPLOYEE
FOR INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE_INSERT_LOG
    (
        EID, FIRSTNAME, LASTNAME,
        SALARY, DEPARTMENT, CITY,
        GENDER,INSERTDATE
    )
    SELECT
        EID, FIRSTNAME, LASTNAME,
        SALARY, DEPARTMENT, CITY,
        GENDER, GETDATE()
    FROM INSERTED
END

DROP TRIGGER TR_EMPLOYEE_INSERT_LOG



--13. Create trigger for storing old and new FIRSTNAME values after employee name update into NAME_CHANGE_LOG table.

CREATE TABLE NAME_CHANGE_LOG
(
    LOGID INT IDENTITY(1,1),
    EID INT,
    OLDFIRSTNAME VARCHAR(100),
    NEWFIRSTNAME VARCHAR(100),
    CHANGEDATE DATETIME
)

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_NAME_CHANGE
ON EMPLOYEE
FOR UPDATE
AS
BEGIN
    IF UPDATE(FIRSTNAME)
    BEGIN
        INSERT INTO NAME_CHANGE_LOG
        (
            EID, OLDFIRSTNAME,
            NEWFIRSTNAME, CHANGEDATE
        )
        SELECT
            D.EID, D.FIRSTNAME,
            I.FIRSTNAME, GETDATE()
        FROM DELETED D
        INNER JOIN INSERTED I
        ON D.EID = I.EID
    END
END

DROP TRIGGER TR_NAME_CHANGE



--14. Create trigger for storing old city and new city details into CITY_UPDATE_LOG table after city update.

CREATE TABLE CITY_UPDATE_LOG
(
    LOGID INT IDENTITY(1,1),
    EID INT,
    OLDCITY VARCHAR(100),
    NEWCITY VARCHAR(100),
    UPDATEDATE DATETIME
)

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_CITY_UPDATE_LOG
ON EMPLOYEE
FOR UPDATE
AS
BEGIN
    IF UPDATE(CITY)
    BEGIN
        INSERT INTO CITY_UPDATE_LOG
        (
            EID, OLDCITY,
            NEWCITY, UPDATEDATE
        )
        SELECT
            D.EID, D.CITY,
            I.CITY, GETDATE()
        FROM DELETED D
        INNER JOIN INSERTED I
        ON D.EID = I.EID
    END
END

DROP TRIGGER TR_CITY_UPDATE_LOG



--15. Implement INSTEAD OF INSERT trigger on EMPLOYEE table to automatically remove extra spaces from FIRSTNAME and LASTNAME before insertion.

--FOR MULTIPLE ROWS

CREATE OR ALTER TRIGGER TR_REMOVE_SPACES
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE
    (
        EID, FIRSTNAME, LASTNAME,
        DEPARTMENT, SALARY, CITY,
        GENDER, JOININGYEAR
    )
    SELECT
        EID,
        LTRIM(RTRIM(FIRSTNAME)),
        LTRIM(RTRIM(LASTNAME)),
        DEPARTMENT, SALARY, CITY,
        GENDER, JOININGYEAR
    FROM INSERTED
END

DROP TRIGGER TR_REMOVE_SPACES
