USE CSE_3A_128

SELECT * FROM STUDENT

--1. Display all students whose SPI is greater than 8.
WITH CTE_SPI AS
(
  SELECT *
  FROM STUDENT
  WHERE SPI > 8
)
SELECT * 
FROM CTE_SPI


--2. Display average SPI of all students.
WITH CTE_AVG_SPI AS
(
  SELECT AVG(SPI) AS AVG_SPI
  FROM STUDENT
)
SELECT AVG_SPI
FROM CTE_AVG_SPI


--3. Display total number of students in each branch.
WITH CTE_BRANCH AS
(
  SELECT BRANCH, 
         COUNT(*) AS C_STUDENT
  FROM STUDENT
  GROUP BY BRANCH
)
SELECT BRANCH , C_STUDENT
FROM CTE_BRANCH


--4. Display students who belong to RAJKOT city.
WITH CTE_CITY AS
(
  SELECT *
  FROM STUDENT
  WHERE CITY = 'RAJKOT'
)
SELECT * 
FROM CTE_CITY


--5. Find branch names that appear more than once.
WITH CTE_BRANCH AS
(
  SELECT BRANCH, 
         COUNT(*) AS TOTAL
  FROM STUDENT
  GROUP BY BRANCH
)
SELECT BRANCH, TOTAL
FROM CTE_BRANCH
WHERE TOTAL > 1


--6. Display row number for each student.
WITH CTE_ROW_NO AS
(
  SELECT *,
  ROW_NUMBER() 
  OVER (ORDER BY SPI DESC) AS ROW_NO
  FROM STUDENT
)
SELECT *
FROM CTE_ROW_NO


--7. Display top 3 students based on SPI.
WITH CTE_TOP3 AS
(
  SELECT *,
  DENSE_RANK() OVER (ORDER BY SPI DESC) AS DRN
  FROM STUDENT
)
SELECT *
FROM CTE_TOP3
WHERE DRN <= 3


--8. Display students having maximum SPI.
WITH CTE_MAX AS
(
  SELECT MAX(SPI) AS MAX_SPI
  FROM STUDENT
)
SELECT S.*
FROM STUDENT S
INNER JOIN CTE_MAX C
ON S.SPI = C.MAX_SPI


--9. Display students having minimum SPI.
WITH CTE_MIN AS
(
    SELECT MIN(SPI) AS MIN_SPI
    FROM STUDENT
)
SELECT S.*
FROM STUDENT S
INNER JOIN CTE_MIN C
ON S.SPI = C.MIN_SPI


--10. Display branch-wise rank of students.
WITH CTE_RANK AS
(
  SELECT *,
  RANK() 
  OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS BRANCH_RANK
  FROM STUDENT
)
SELECT *
FROM CTE_RANK


--11. Display students SPI average belonging to Computer branch.
WITH CTE_COMPUTER_AVG AS
(
  SELECT AVG(SPI) AS AVG_SPI
  FROM STUDENT
  WHERE BRANCH = 'COMPUTER'
)
SELECT AVG_SPI
FROM CTE_COMPUTER_AVG


--12. Display students whose SPI is greater than average SPI of his/her branch.
WITH CTE_BRANCH_AVG AS
(
  SELECT BRANCH,
         AVG(SPI) AS AVG_SPI
  FROM STUDENT
  GROUP BY BRANCH
)
SELECT S.*
FROM STUDENT S
INNER JOIN CTE_BRANCH_AVG C
ON S.BRANCH = C.BRANCH
WHERE S.SPI > C.AVG_SPI


--13. Display branch having more than 2 students.
WITH CTE_BRANCH AS
(
  SELECT BRANCH,
         COUNT(*) AS TOTAL_STUDENTS
  FROM STUDENT
  GROUP BY BRANCH
)
SELECT *
FROM CTE_BRANCH
WHERE TOTAL_STUDENTS > 2


--14. Display branches having average SPI between 7 and 9
WITH CTE_BRANCH_AVG AS
(
  SELECT BRANCH,
         AVG(SPI) AS AVG_SPI
  FROM STUDENT
  GROUP BY BRANCH
)
SELECT *
FROM CTE_BRANCH_AVG
WHERE AVG_SPI BETWEEN 7 AND 9


--15. Display students whose SPI is lower than overall average SPI.
WITH CTE_AVG_SPI AS
(
  SELECT AVG(SPI) AS OVERALL_AVG_SPI
  FROM STUDENT
)
SELECT S.*
FROM STUDENT S
CROSS JOIN CTE_AVG_SPI C
WHERE S.SPI < C.OVERALL_AVG_SPI


--16. Display branches having exactly one student.
WITH CTE_BRANCH AS
(
  SELECT BRANCH,
         COUNT(*) AS TOTAL_STUDENTS
  FROM STUDENT
  GROUP BY BRANCH
)
SELECT *
FROM CTE_BRANCH
WHERE TOTAL_STUDENTS = 1


--17. Display branch having highest average SPI.
WITH CTE_BRANCH_AVG AS
(
  SELECT BRANCH,
         AVG(SPI) AS AVG_SPI
  FROM STUDENT
  GROUP BY BRANCH
),
CTE_MAX AS
(
  SELECT MAX(AVG_SPI) AS MAX_AVG_SPI
  FROM CTE_BRANCH_AVG
)
SELECT B.*
FROM CTE_BRANCH_AVG B
INNER JOIN CTE_MAX M
ON B.AVG_SPI = M.MAX_AVG_SPI


-- 18. Display branch having lowest average SPI.
WITH CTE_BRANCH_AVG AS
(
  SELECT BRANCH,
         AVG(SPI) AS AVG_SPI
  FROM STUDENT
  WHERE BRANCH IS NOT NULL
  GROUP BY BRANCH
),
CTE_MIN AS
(
  SELECT MIN(AVG_SPI) AS MIN_AVG_SPI
  FROM CTE_BRANCH_AVG
)
SELECT B.*
FROM CTE_BRANCH_AVG B
INNER JOIN CTE_MIN M
ON B.AVG_SPI = M.MIN_AVG_SPI


-- 19. Display students whose SPI is lower than branch average SPI.
WITH CTE_BRANCH_AVG AS
(
  SELECT BRANCH,
         AVG(SPI) AS AVG_SPI
  FROM STUDENT
  GROUP BY BRANCH
)
SELECT S.*
FROM STUDENT S
INNER JOIN CTE_BRANCH_AVG C
ON S.BRANCH = C.BRANCH
WHERE S.SPI < C.AVG_SPI


-- 20. Display branches having maximum number of students.
WITH CTE_BRANCH AS
(
  SELECT BRANCH,
         COUNT(*) AS TOTAL_STUDENTS
  FROM STUDENT
  GROUP BY BRANCH
),
CTE_MAX AS
(
  SELECT MAX(TOTAL_STUDENTS) AS MAX_STUDENTS
  FROM CTE_BRANCH
)
SELECT B.*
FROM CTE_BRANCH B
INNER JOIN CTE_MAX M
ON B.TOTAL_STUDENTS = M.MAX_STUDENTS

-------- OR --------

WITH CTE_BRANCH AS
(
  SELECT BRANCH,
         COUNT(STDID) AS B_COUNT
  FROM STUDENT
  GROUP BY BRANCH
)
SELECT TOP 1 B_COUNT,BRANCH
FROM CTE_BRANCH
ORDER BY B_COUNT DESC















