USE CSE_3A_128

SELECT * FROM PUBLISHER
SELECT * FROM AUTHOR
SELECT * FROM BOOK

--1. List all books with their authors.
SELECT B.TITLE , A.AUTHORNAME 
FROM BOOK B 
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID

--2. List all books with their publishers.
SELECT B.TITLE , P.PUBLISHERNAME
FROM BOOK B 
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--3. List all books with their authors and publishers.
SELECT B.TITLE , A.AUTHORNAME ,P.PUBLISHERNAME
FROM PUBLISHER P 
INNER JOIN BOOK B 
ON P.PUBLISHERID = B.PUBLISHERID
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID

--4. List all books published after 2010 with their authors and publisher and price.
SELECT B.TITLE , A.AUTHORNAME ,P.PUBLISHERNAME , B.PRICE
FROM PUBLISHER P 
INNER JOIN BOOK B 
ON P.PUBLISHERID = B.PUBLISHERID
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
WHERE B.PUBLICATIONYEAR > 2010

--5. List all authors and the number of books they have written.
SELECT A.AUTHORNAME ,COUNT(BOOKID) AS TOTAL_WRITTEN_BOOKS
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
GROUP BY A.AUTHORNAME

--6. List all publishers and the total price of books they have published.
SELECT P.PUBLISHERNAME , SUM(B.PRICE) AS TOTAL_PRICE
FROM PUBLISHER P 
INNER JOIN BOOK B 
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME

--7. List authors who have not written any books.
SELECT A.AUTHORNAME
FROM AUTHOR A
LEFT JOIN BOOK B
ON B.AUTHORID = A.AUTHORID
WHERE B.BOOKID IS NULL

--8. Display the total number of books written by each author along with the average price of their books.
SELECT A.AUTHORNAME ,COUNT(BOOKID) AS TOTAL_WRITTEN_BOOKS, AVG(B.PRICE) AS AVG_PRICE
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
GROUP BY A.AUTHORNAME

--9. lists each publisher along with the total number of books they have published, sorted from highest to lowest.
SELECT P.PUBLISHERNAME , COUNT(B.BOOKID) AS TOTAL_BOOKS
FROM PUBLISHER P 
INNER JOIN BOOK B 
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME
ORDER BY TOTAL_BOOKS DESC

--10. Display number of books published each year.
SELECT B.PUBLICATIONYEAR , COUNT(B.BOOKID) AS TOTAL_BOOKS
FROM BOOK B 
INNER JOIN PUBLISHER P
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY B.PUBLICATIONYEAR

--11. List the publishers whose total book prices exceed 500, ordered by the total price.
SELECT P.PUBLISHERNAME , SUM(B.PRICE) AS TOTAL_PRICE
FROM PUBLISHER P
LEFT JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME
HAVING SUM(B.PRICE) > 500
ORDER BY TOTAL_PRICE

--12. List most expensive book for each author, sort it with the highest price.
SELECT A.AUTHORNAME , MAX(B.PRICE) AS EXPENCIVE_BOOK_PRICE
FROM AUTHOR A
INNER JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME
ORDER BY EXPENCIVE_BOOK_PRICE DESC

--13. Display publisher name and difference between maximum and minimum book price.
SELECT P.PUBLISHERNAME , MAX(B.PRICE)- MIN(B.PRICE) AS DIFF_PRICE
FROM PUBLISHER P
INNER JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME

--14. List publisher name and total price of books published each year.
SELECT P.PUBLISHERNAME ,B.PUBLICATIONYEAR , SUM(B.PRICE) AS TOTAL_PRICE 
FROM PUBLISHER P
INNER JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME , PUBLICATIONYEAR

--15. Display author name and total price of books sorted by highest total price.
SELECT A.AUTHORNAME , SUM(B.PRICE) AS TOTAL_PRICE 
FROM AUTHOR A
INNER JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME
ORDER BY TOTAL_PRICE DESC

--EMPLOYEE_MASTER

CREATE TABLE EMPLOYEE_MASTER
(
	EMPLOYEENO CHAR(3),
	NAME VARCHAR(20),
	MANAGERNO CHAR(3)
);

INSERT INTO EMPLOYEE_MASTER
VALUES ('E01','TARUN',NULL),
	('E02','ROHAN','E02'),
	('E03','PRIYA','E01'),
	('E04','MILAN','E03'),
	('E05','JAY','E01'),
	('E06','ANJANA','E04')

SELECT * FROM EMPLOYEE_MASTER

--16. Retrieve the names of employee along with their manager’s name from the Employee table.
SELECT E.NAME AS EMPLOYEE_NAME, M.NAME AS MANAGER_NAME
FROM EMPLOYEE_MASTER E 
INNER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO

--17. Display employees who are managers.
SELECT E.NAME AS EMPLOYEE_NAME
FROM EMPLOYEE_MASTER E 
INNER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO

-- 18. Display number of employees working under each manager.
SELECT M.NAME AS MANAGER_NAME, COUNT(E.EMPLOYEENO) AS TOTAL_EMPLOYEES
FROM EMPLOYEE_MASTER E 
INNER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO 
GROUP BY M.NAME

-- 19. Display the employee’s name along with their manager’s name and senior manager name.
SELECT E.NAME AS EMPLOYEE_NAME, M.NAME AS MANAGER_NAME, SM.NAME AS SENIOR_MANAGER_NAME 
FROM EMPLOYEE_MASTER E 
LEFT JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO 
LEFT JOIN EMPLOYEE_MASTER SM
ON M.MANAGERNO = SM.EMPLOYEENO

-- 20. Display managers and count of employees under them in descending order.
SELECT M.NAME AS MANAGER_NAME, COUNT(E.EMPLOYEENO) AS TOTAL_EMPLOYEES 
FROM EMPLOYEE_MASTER E 
INNER JOIN EMPLOYEE_MASTER M 
ON E.MANAGERNO = M.EMPLOYEENO 
GROUP BY M.NAME 
ORDER BY TOTAL_EMPLOYEES DESC
