USE CSE_3A_128

--CUSTOMER_ALL

CREATE TABLE CUSTOMER_ALL
(
	ORDERID INT,
	CNAME VARCHAR(15),
	[PRODUCT] VARCHAR(15),
	CATEGORY VARCHAR(15),
	AMOUNT INT,
	ORDERYEAR INT,
	CITY VARCHAR(15)
);

INSERT INTO CUSTOMER_ALL
VALUES (101, 'RAHUL', 'LAPTOP', 'ELECTRONICS', 65000, 2024, 'RAJKOT'),
	(102, 'PRIYA', 'MOBILE', 'ELECTRONICS', 25000, 2023, 'SURAT'),
	(103, 'AMIT', 'TABLE', 'FURNITURE', 12000, 2022, 'AHMEDABAD'),
	(104, 'NEHA', 'CHAIR', 'FURNITURE', 8000, 2024, 'BARODA'),
	(105, 'VISHAL', 'TV', 'ELECTRONICS', 45000, 2025, 'MORBI'),
	(106, 'RIYA', 'SOFA', 'FURNITURE', 30000, 2023, 'SURAT'),
	(107, 'MEHUL', 'AC', 'ELECTRONICS', 40000, 2022, 'RAJKOT'),
	(108, 'KRUNAL', 'BED', 'FURNITURE', 40000, 2025, 'JAMNAGAR')

SELECT * FROM CUSTOMER_ALL


--1. Display top 3 highest amount orders.
WITH CTE_TOP3 AS
(
  SELECT *,
  DENSE_RANK()
  OVER (ORDER BY AMOUNT DESC) AS AMOUNT_RANK
  FROM CUSTOMER_ALL
)
SELECT *
FROM CTE_TOP3
WHERE AMOUNT_RANK <= 3


--2. Display second highest order amount.
WITH CTE_2_HIGHEST AS
(
  SELECT *,
  DENSE_RANK()
  OVER (ORDER BY AMOUNT DESC) AS AMOUNT_RANK
  FROM CUSTOMER_ALL
)
SELECT *
FROM CTE_2_HIGHEST
WHERE AMOUNT_RANK = 2


--3. Display customers whose order amount is greater than category average amount.
WITH CTE_AMOUNT AS
(
  SELECT CATEGORY ,
		 AVG(AMOUNT) AS AVG_AMOUNT
  FROM CUSTOMER_ALL
  GROUP BY CATEGORY
)
SELECT CA.*
FROM CUSTOMER_ALL CA
INNER JOIN CTE_AMOUNT C
ON CA.CATEGORY = C.CATEGORY
WHERE AMOUNT > AVG_AMOUNT


--4. Display categories having average amount greater than 30000.
WITH CTE_CATEGORY_AMOUNT AS
(
  SELECT CATEGORY ,
		 AVG(AMOUNT) AS AVG_AMOUNT
  FROM CUSTOMER_ALL
  GROUP BY CATEGORY
)
SELECT CATEGORY , AVG_AMOUNT
FROM CTE_CATEGORY_AMOUNT
WHERE AVG_AMOUNT > 30000


--5. Display highest amount order from each category.
WITH CTE_HIGH_AMOUNT AS
(
  SELECT *,
  DENSE_RANK()
  OVER(PARTITION BY CATEGORY ORDER BY AMOUNT DESC) AS HA_RANK
  FROM CUSTOMER_ALL
)
SELECT *
FROM CTE_HIGH_AMOUNT
WHERE HA_RANK = 1


--6. Display lowest amount order from each category.
WITH CTE_LOW_AMOUNT AS
(
  SELECT *,
  DENSE_RANK()
  OVER(PARTITION BY CATEGORY ORDER BY AMOUNT ASC) AS LA_RANK
  FROM CUSTOMER_ALL
)
SELECT *
FROM CTE_LOW_AMOUNT
WHERE LA_RANK = 1


--7. Display categories having more than 3 orders.
WITH CTE_COUNT_ORDER AS
(
  SELECT CATEGORY ,
		 COUNT(*) AS TOTAL_ORDER
  FROM CUSTOMER_ALL
  GROUP BY CATEGORY
)
SELECT CATEGORY ,TOTAL_ORDER
FROM CTE_COUNT_ORDER
WHERE TOTAL_ORDER > 3


--8. Display city-wise total order amount.
WITH CTE_CITY_AMOUNT AS
(
  SELECT CITY ,
		 SUM(AMOUNT) AS TOTAL_AMOUNT
  FROM CUSTOMER_ALL
  GROUP BY CITY
)
SELECT CITY , TOTAL_AMOUNT
FROM CTE_CITY_AMOUNT


--9. Display category having highest average order amount.
WITH CTE_HIGH_AVG_AMOUNT AS
(
  SELECT CATEGORY ,
		 AVG(AMOUNT) AS AVG_ORDER
  FROM CUSTOMER_ALL
  GROUP BY CATEGORY
)
SELECT TOP 1 CATEGORY , AVG_ORDER
FROM CTE_HIGH_AVG_AMOUNT
ORDER BY AVG_ORDER DESC


--10. Display cumulative order amount in ascending order of amount.
WITH CTE_CUMULATIVE AS
(
  SELECT *, SUM(AMOUNT) 
  OVER(ORDER BY AMOUNT) AS TOTAL
  FROM CUSTOMER_ALL
)
SELECT * 
FROM CTE_CUMULATIVE


--11. Display category-wise top 2 highest amount orders.
WITH CTE_CATEGORY_AMOUNT AS
(
  SELECT *,
  DENSE_RANK()
  OVER(PARTITION BY CATEGORY ORDER BY AMOUNT DESC) AS A_RANK
  FROM CUSTOMER_ALL
)
SELECT *
FROM CTE_CATEGORY_AMOUNT
WHERE A_RANK <= 2


--12. Display customers whose amount is closest to category average amount.
WITH CTE_CLOSET AS
(
  SELECT AVG(AMOUNT) AS AVG_AMOUNT
  FROM CUSTOMER_ALL
  GROUP BY CATEGORY
),
CTE_DIFFERENCE AS
(
  SELECT * , ABS(AMOUNT - AVG_AMOUNT) AS DIFF_AMOUNT
  FROM CUSTOMER_ALL
  CROSS JOIN CTE_CLOSET
)
SELECT TOP 1 * 
FROM CTE_DIFFERENCE
ORDER BY DIFF_AMOUNT

---------- OR ----------

WITH CTE_CLOSET AS
(
  SELECT * , AVG(AMOUNT) 
  OVER(PARTITION BY CATEGORY)AS AVG_AMOUNT
  FROM CUSTOMER_ALL
),
CTE_DIFFERENCE AS
(
  SELECT * , ABS(AMOUNT - AVG_AMOUNT) AS DIFF_AMOUNT,
  RANK() 
  OVER(ORDER BY ABS(AMOUNT - AVG_AMOUNT)) AS RN
  FROM CTE_CLOSET
)
SELECT * 
FROM CTE_DIFFERENCE
WHERE RN = 1


--13. Display previous, current and next order amount together.
SELECT * , 
LAG(AMOUNT)
OVER(ORDER BY AMOUNT) AS PREVIOUS_AMOUNT,
LEAD(AMOUNT)
OVER(ORDER BY AMOUNT) AS PREVIOUS_AMOUNT
FROM CUSTOMER_ALL


--14. Display customers whose amount is greater than previous customer's amount.
WITH CTE_PREVIOUS AS
(
  SELECT *,
  LAG(AMOUNT)
  OVER(ORDER BY AMOUNT) AS PREVIOUS_AMOUNT
  FROM CUSTOMER_ALL
)
SELECT * 
FROM CTE_PREVIOUS
WHERE AMOUNT > PREVIOUS_AMOUNT


--15. Display customers whose rank and dense rank are different.
WITH CTE_DIFF AS
(
  SELECT * ,
  DENSE_RANK()
  OVER(ORDER BY AMOUNT) AS D_RANK,
  RANK()
  OVER(ORDER BY AMOUNT) AS N_RANK
  FROM CUSTOMER_ALL
)
SELECT *
FROM CTE_DIFF
WHERE D_RANK <> N_RANK


--16. Display orders whose amount is neither highest nor lowest in their category.
WITH CTE_AMOUNT AS
(
  SELECT *, 
  MAX(AMOUNT) 
  OVER(PARTITION BY CATEGORY) AS FIRST_AMOUNT,
  MIN(AMOUNT) 
  OVER(PARTITION BY CATEGORY) AS LAST_AMOUNT
  FROM CUSTOMER_ALL
)
SELECT * 
FROM CTE_AMOUNT
WHERE AMOUNT <> FIRST_AMOUNT AND AMOUNT <> LAST_AMOUNT


--17. Display category-wise difference between highest and lowest amount.
WITH CTE_DIFF AS
(
  SELECT CATEGORY, 
  (MAX(AMOUNT) - MIN(AMOUNT)) AS DIFF
  FROM CUSTOMER_ALL
  GROUP BY CATEGORY
)
SELECT * 
FROM CTE_DIFF


--18. Display customers whose amount is greater than all FURNITURE category orders.
WITH CTE_FURNITURE AS
(
  SELECT MAX(AMOUNT) AS MAX_AMOUNT
  FROM CUSTOMER_ALL
  WHERE CATEGORY = 'FURNITURE'
)
SELECT *
FROM CUSTOMER_ALL CA
CROSS JOIN CTE_FURNITURE C
WHERE CA.AMOUNT > C.MAX_AMOUNT


--19. Display categories where all orders are above 10000.
WITH CTE_CATEGORY AS
(
  SELECT CATEGORY , MIN(AMOUNT) AS MIN_AMOUNT
  FROM CUSTOMER_ALL
  GROUP BY CATEGORY
)
SELECT CATEGORY 
FROM CTE_CATEGORY
WHERE MIN_AMOUNT > 10000


--20. Display customers whose amount difference from category topper is minimum.
WITH CTE_TOPPER AS (
    SELECT * , MAX(AMOUNT) 
	OVER(PARTITION BY CATEGORY) AS MAX_AMOUNT
    FROM CUSTOMER_ALL
),
CTE_DIFF AS (
    SELECT * ,
    (MAX_AMOUNT - AMOUNT) AS AMOUNT_DIFF
    FROM CTE_TOPPER
)
SELECT *
FROM CTE_DIFF
WHERE AMOUNT_DIFF = 0
